on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' 

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          make provisioning && make build && ls -la
